all:
  hut_statuses:
    list:
      0:
      2: opened staffed
      4: opened unstaffed
      6: closed hut

  frequentation_statuses:
    list:
      0:
      1: desert
      2: some people
      4: quite crowded
      3: lots of people

  conditions_statuses:
    list:
      0:
      1: excellent conditions
      2: good conditions
      3: mean conditions
      4: poor conditions
      5: awful conditions

  access_statuses:
    list:
      0:
      2: cleared road
      4: snowy road
      6: closed road
  
  lift_statuses:
    list:
      0:
      2: opened lift
      4: closed lift

  glacier_statuses:
    list:
      0:
      2: easy crossing
      4: possible crossing
      6: difficult crossing
      8: impossible crossing

  track_statuses:
    list:
      0:
      1: good track
      2: mean track
      3: poor track

  conditions_levels:
    fields:
      1: level_place
      2: level_snow_height_soft
      3: level_snow_height_total
      4: level_comment

  sort:
    attributes:
     - 'data-act-filter'
    criteria:
      'id': ID
      'onam': name
      'act':  activities
      'date': date short
      'cond': conditions_status
      'range': ranges
      'admin': admin_limits
      'country': countries
      'lat': 'location S >> N'
      'lon': 'location W >> E'
      'alt':  max_elevation
      'fac': facing
      'hdif': height_diff_up
      'ddif': height_diff_down
      'time': duration
      'ralt': difficulties_start_elevation
      'dhei': difficulties_height
      'grat': global_rating
      'erat': engagement_rating
      'orrat': objective_risk_rating
      'prat': equipment_rating
      'rexpo': rock_exposition_rating
      'frat': rock_free_rating
      'rrat': rock_required_rating
      'arat': aid_rating
      'irat': ice_rating
      'mrat': mixed_rating
      'trat': toponeige_technical_rating
      'sexpo': toponeige_exposition_rating
      'lrat': labande_global_rating
      'srat': labande_ski_rating
      'hrat': hiking_rating
      'wrat': snowshoeing_rating
    'data-act-filter':
      'act':   'multi'       # activities
      'alt':   '1 2 3 4 6 7' # max_elevation
      'hdif':  '1 2 3 4 6 7' # height_diff_up
      'ddif':  '1'           # height_diff_down
      'time':  '1 2 3 4 6 7' # duration
      'ralt':  '1 2 3 4 5'   # difficulties_start_elevation
      'dhei':  '1 2 3 4 5'   # difficulties_height
      'grat':  '2 3 4 5'     # global_rating
      'erat':  '2 3 4 5'     # engagement_rating
      'orrat': '2 3 5'       # objective_risk_rating
      'prat':  '2 3 4 5'     # equipment_rating
      'rexpo': '3 4'         # rock_exposition_rating
      'frat':  '3 4'         # rock_free_rating
      'rrat':  '3 4'         # rock_required_rating
      'arat':  '3 4'         # aid_rating
      'irat':  '2 5'         # ice_rating
      'mrat':  '2 5'         # mixed_rating
      'trat':  '1'           # toponeige_technical_rating
      'sexpo': '1'           # toponeige_exposition_rating
      'lrat':  '1'           # labande_global_rating
      'srat':  '1'           # labande_ski_rating
      'hrat':  '6'           # hiking_rating
      'wrat':  '7'           # snowshoeing_rating
      'rlen':  '6'           # route_length
    route_criteria: [ 'fac', 'time', 'ralt', 'dhei', 'grat', 'erat', 'orrat', 'prat', 'frat', 'rrat', 'arat', 'rexpo', 'irat', 'mrat', 'trat', 'sexpo', 'lrat', 'srat', 'hrat', 'wrat' ]
    filled_criteria:
      'alt':  oalt
      'hdif': odif
      'ddif': oddif
      'usnow': ousnow
      'dsnow': odsnow
      'access': oaccess
      'cond': ocond
      'freq': ofreq
      'park': opark
      'glac': oglac
      'track': otrack
      'hut': ohut
      'lift': olift
      'fac': ''
      'time': ''
      'ralt': ''
      'dhei': ''
      'grat': ''
      'erat': ''
      'orrat': ''
      'prat': ''
      'rexpo': ''
      'frat': ''
      'rrat': ''
      'arat': ''
      'irat': ''
      'mrat': ''
      'trat': ''
      'sexpo': ''
      'lrat': ''
      'srat': ''
      'hrat': ''
      'wrat': ''
  
  recent_conditions_limit: 3W

  # duplicated from routes config, so that it can be used
  # as a search criteria for outings
  sub_activities:
    list:
      0:
      2: snowboard
      4: beginner_proof
      6: vtt_approach
      8: lift_approach
  
  activities_type:
    list:
      0:
      1: 'for outings'
      2: 'for linked routes'
